#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: absa-install-k8s-builder
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      name: absa-install-k8s-builder
    spec:
      restartPolicy: "Never"
      containers:
        - name: main
          image: ${K8S_CHAINCODE_BUILDER_IMAGE}:${K8S_CHAINCODE_BUILDER_VERSION}
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "mkdir -p /mnt/fabric-absa/fabric/external_builders && cp -rv /opt/hyperledger/k8s_builder /mnt/fabric-absa/fabric/external_builders/"
          volumeMounts:
            - name: fabric-absa-volume
              mountPath: /mnt/fabric-absa
      volumes:
        - name: fabric-absa-volume
          persistentVolumeClaim:
            claimName: fabric-absa
